### ISSUE TITLE
Completions

### ISSUE THREAD

**Issue by BryanSchuetz** [arthrfrts/Liquid.novaextension#4]
For me, completions only become available when the cursor is inside a liquid tag. Can we make them available anywhere in files with an HTML (Liquid) syntax? Not totally sure how this all works in Nova—just now switching over from VSCode.

**Comment by BryanSchuetz** [comment]
Actually, I kind of see the value in this now to prevent pollution of the completions list everywhere else in the file. This actually makes a lot of sense I think. Closing. Sorry.

**Comment by arthrfrts** [comment]
Hmm, completions are in early stages, really, and is something I actually struggle to make sense of. Should the editor give you all the relevant suggestions all the times?

That's something I struggle with since I mainly write my code without using this kind of features.

If you have any suggestion on how to make completions work in a better way (and that Nova supports), let's talk! I would love to hear it from someone who actually uses this feature.
